export type BibleBook = {
  id: string;
  name: string;
  shortName: string;
  abbreviations: string[];
  testament: "old" | "new";
  chapterCount: number;
  isSingleChapter: boolean;
};

/**
 * Canonical list of all 66 Bible books with metadata.
 * Book IDs follow the ESV API's standard abbreviation scheme.
 * Abbreviations include common short forms used in passage strings.
 */
export const BIBLE_BOOKS: readonly BibleBook[] = [
  // Old Testament
  {
    id: "GEN",
    name: "Genesis",
    shortName: "Gen",
    abbreviations: ["Gen", "Ge", "Gn"],
    testament: "old",
    chapterCount: 50,
    isSingleChapter: false,
  },
  {
    id: "EXO",
    name: "Exodus",
    shortName: "Exod",
    abbreviations: ["Exod", "Ex", "Exo"],
    testament: "old",
    chapterCount: 40,
    isSingleChapter: false,
  },
  {
    id: "LEV",
    name: "Leviticus",
    shortName: "Lev",
    abbreviations: ["Lev", "Le", "Lv"],
    testament: "old",
    chapterCount: 27,
    isSingleChapter: false,
  },
  {
    id: "NUM",
    name: "Numbers",
    shortName: "Num",
    abbreviations: ["Num", "Nu", "Nm"],
    testament: "old",
    chapterCount: 36,
    isSingleChapter: false,
  },
  {
    id: "DEU",
    name: "Deuteronomy",
    shortName: "Deut",
    abbreviations: ["Deut", "De", "Dt"],
    testament: "old",
    chapterCount: 34,
    isSingleChapter: false,
  },
  {
    id: "JOS",
    name: "Joshua",
    shortName: "Josh",
    abbreviations: ["Josh", "Jos"],
    testament: "old",
    chapterCount: 24,
    isSingleChapter: false,
  },
  {
    id: "JDG",
    name: "Judges",
    shortName: "Judg",
    abbreviations: ["Judg", "Jdg"],
    testament: "old",
    chapterCount: 21,
    isSingleChapter: false,
  },
  {
    id: "RUT",
    name: "Ruth",
    shortName: "Ruth",
    abbreviations: ["Ruth", "Ru"],
    testament: "old",
    chapterCount: 4,
    isSingleChapter: false,
  },
  {
    id: "1SA",
    name: "1 Samuel",
    shortName: "1 Sam",
    abbreviations: ["1Sam", "1Sa", "1 Sam", "1 Samuel"],
    testament: "old",
    chapterCount: 31,
    isSingleChapter: false,
  },
  {
    id: "2SA",
    name: "2 Samuel",
    shortName: "2 Sam",
    abbreviations: ["2Sam", "2Sa", "2 Sam", "2 Samuel"],
    testament: "old",
    chapterCount: 24,
    isSingleChapter: false,
  },
  {
    id: "1KI",
    name: "1 Kings",
    shortName: "1 Kgs",
    abbreviations: ["1Kgs", "1Ki", "1 Kings", "1 Kgs"],
    testament: "old",
    chapterCount: 22,
    isSingleChapter: false,
  },
  {
    id: "2KI",
    name: "2 Kings",
    shortName: "2 Kgs",
    abbreviations: ["2Kgs", "2Ki", "2 Kings", "2 Kgs"],
    testament: "old",
    chapterCount: 25,
    isSingleChapter: false,
  },
  {
    id: "1CH",
    name: "1 Chronicles",
    shortName: "1 Chr",
    abbreviations: ["1Chr", "1Ch", "1 Chronicles", "1 Chr"],
    testament: "old",
    chapterCount: 29,
    isSingleChapter: false,
  },
  {
    id: "2CH",
    name: "2 Chronicles",
    shortName: "2 Chr",
    abbreviations: ["2Chr", "2Ch", "2 Chronicles", "2 Chr"],
    testament: "old",
    chapterCount: 36,
    isSingleChapter: false,
  },
  {
    id: "EZR",
    name: "Ezra",
    shortName: "Ezra",
    abbreviations: ["Ezra", "Ezr"],
    testament: "old",
    chapterCount: 10,
    isSingleChapter: false,
  },
  {
    id: "NEH",
    name: "Nehemiah",
    shortName: "Neh",
    abbreviations: ["Neh", "Ne"],
    testament: "old",
    chapterCount: 13,
    isSingleChapter: false,
  },
  {
    id: "EST",
    name: "Esther",
    shortName: "Esth",
    abbreviations: ["Esth", "Est", "Es"],
    testament: "old",
    chapterCount: 10,
    isSingleChapter: false,
  },
  {
    id: "JOB",
    name: "Job",
    shortName: "Job",
    abbreviations: ["Job", "Jb"],
    testament: "old",
    chapterCount: 42,
    isSingleChapter: false,
  },
  {
    id: "PSA",
    name: "Psalms",
    shortName: "Ps",
    abbreviations: ["Ps", "Psa", "Psalm", "Psalms"],
    testament: "old",
    chapterCount: 150,
    isSingleChapter: false,
  },
  {
    id: "PRO",
    name: "Proverbs",
    shortName: "Prov",
    abbreviations: ["Prov", "Pr", "Pro"],
    testament: "old",
    chapterCount: 31,
    isSingleChapter: false,
  },
  {
    id: "ECC",
    name: "Ecclesiastes",
    shortName: "Eccl",
    abbreviations: ["Eccl", "Ecc", "Ec"],
    testament: "old",
    chapterCount: 12,
    isSingleChapter: false,
  },
  {
    id: "SNG",
    name: "Song of Solomon",
    shortName: "Song",
    abbreviations: ["Song", "SS", "SOS", "Song of Solomon", "Song of Songs"],
    testament: "old",
    chapterCount: 8,
    isSingleChapter: false,
  },
  {
    id: "ISA",
    name: "Isaiah",
    shortName: "Isa",
    abbreviations: ["Isa", "Is"],
    testament: "old",
    chapterCount: 66,
    isSingleChapter: false,
  },
  {
    id: "JER",
    name: "Jeremiah",
    shortName: "Jer",
    abbreviations: ["Jer", "Je"],
    testament: "old",
    chapterCount: 52,
    isSingleChapter: false,
  },
  {
    id: "LAM",
    name: "Lamentations",
    shortName: "Lam",
    abbreviations: ["Lam", "La"],
    testament: "old",
    chapterCount: 5,
    isSingleChapter: false,
  },
  {
    id: "EZK",
    name: "Ezekiel",
    shortName: "Ezek",
    abbreviations: ["Ezek", "Eze", "Ezk"],
    testament: "old",
    chapterCount: 48,
    isSingleChapter: false,
  },
  {
    id: "DAN",
    name: "Daniel",
    shortName: "Dan",
    abbreviations: ["Dan", "Da", "Dn"],
    testament: "old",
    chapterCount: 12,
    isSingleChapter: false,
  },
  {
    id: "HOS",
    name: "Hosea",
    shortName: "Hos",
    abbreviations: ["Hos", "Ho"],
    testament: "old",
    chapterCount: 14,
    isSingleChapter: false,
  },
  {
    id: "JOL",
    name: "Joel",
    shortName: "Joel",
    abbreviations: ["Joel", "Jl"],
    testament: "old",
    chapterCount: 3,
    isSingleChapter: false,
  },
  {
    id: "AMO",
    name: "Amos",
    shortName: "Amos",
    abbreviations: ["Amos", "Am"],
    testament: "old",
    chapterCount: 9,
    isSingleChapter: false,
  },
  {
    id: "OBA",
    name: "Obadiah",
    shortName: "Obad",
    abbreviations: ["Obad", "Ob"],
    testament: "old",
    chapterCount: 1,
    isSingleChapter: true,
  },
  {
    id: "JON",
    name: "Jonah",
    shortName: "Jonah",
    abbreviations: ["Jonah", "Jon"],
    testament: "old",
    chapterCount: 4,
    isSingleChapter: false,
  },
  {
    id: "MIC",
    name: "Micah",
    shortName: "Mic",
    abbreviations: ["Mic", "Mi"],
    testament: "old",
    chapterCount: 7,
    isSingleChapter: false,
  },
  {
    id: "NAM",
    name: "Nahum",
    shortName: "Nah",
    abbreviations: ["Nah", "Na"],
    testament: "old",
    chapterCount: 3,
    isSingleChapter: false,
  },
  {
    id: "HAB",
    name: "Habakkuk",
    shortName: "Hab",
    abbreviations: ["Hab"],
    testament: "old",
    chapterCount: 3,
    isSingleChapter: false,
  },
  {
    id: "ZEP",
    name: "Zephaniah",
    shortName: "Zeph",
    abbreviations: ["Zeph", "Zep"],
    testament: "old",
    chapterCount: 3,
    isSingleChapter: false,
  },
  {
    id: "HAG",
    name: "Haggai",
    shortName: "Hag",
    abbreviations: ["Hag"],
    testament: "old",
    chapterCount: 2,
    isSingleChapter: false,
  },
  {
    id: "ZEC",
    name: "Zechariah",
    shortName: "Zech",
    abbreviations: ["Zech", "Zec"],
    testament: "old",
    chapterCount: 14,
    isSingleChapter: false,
  },
  {
    id: "MAL",
    name: "Malachi",
    shortName: "Mal",
    abbreviations: ["Mal"],
    testament: "old",
    chapterCount: 4,
    isSingleChapter: false,
  },
  // New Testament
  {
    id: "MAT",
    name: "Matthew",
    shortName: "Matt",
    abbreviations: ["Matt", "Mt", "Mat"],
    testament: "new",
    chapterCount: 28,
    isSingleChapter: false,
  },
  {
    id: "MRK",
    name: "Mark",
    shortName: "Mark",
    abbreviations: ["Mark", "Mk", "Mr"],
    testament: "new",
    chapterCount: 16,
    isSingleChapter: false,
  },
  {
    id: "LUK",
    name: "Luke",
    shortName: "Luke",
    abbreviations: ["Luke", "Lk", "Lu"],
    testament: "new",
    chapterCount: 24,
    isSingleChapter: false,
  },
  {
    id: "JHN",
    name: "John",
    shortName: "John",
    abbreviations: ["John", "Jn", "Joh"],
    testament: "new",
    chapterCount: 21,
    isSingleChapter: false,
  },
  {
    id: "ACT",
    name: "Acts",
    shortName: "Acts",
    abbreviations: ["Acts", "Ac"],
    testament: "new",
    chapterCount: 28,
    isSingleChapter: false,
  },
  {
    id: "ROM",
    name: "Romans",
    shortName: "Rom",
    abbreviations: ["Rom", "Ro"],
    testament: "new",
    chapterCount: 16,
    isSingleChapter: false,
  },
  {
    id: "1CO",
    name: "1 Corinthians",
    shortName: "1 Cor",
    abbreviations: ["1Cor", "1Co", "1 Corinthians", "1 Cor", "1Corinthians"],
    testament: "new",
    chapterCount: 16,
    isSingleChapter: false,
  },
  {
    id: "2CO",
    name: "2 Corinthians",
    shortName: "2 Cor",
    abbreviations: ["2Cor", "2Co", "2 Corinthians", "2 Cor", "2Corinthians"],
    testament: "new",
    chapterCount: 13,
    isSingleChapter: false,
  },
  {
    id: "GAL",
    name: "Galatians",
    shortName: "Gal",
    abbreviations: ["Gal", "Ga"],
    testament: "new",
    chapterCount: 6,
    isSingleChapter: false,
  },
  {
    id: "EPH",
    name: "Ephesians",
    shortName: "Eph",
    abbreviations: ["Eph"],
    testament: "new",
    chapterCount: 6,
    isSingleChapter: false,
  },
  {
    id: "PHP",
    name: "Philippians",
    shortName: "Phil",
    abbreviations: ["Phil", "Php"],
    testament: "new",
    chapterCount: 4,
    isSingleChapter: false,
  },
  {
    id: "COL",
    name: "Colossians",
    shortName: "Col",
    abbreviations: ["Col"],
    testament: "new",
    chapterCount: 4,
    isSingleChapter: false,
  },
  {
    id: "1TH",
    name: "1 Thessalonians",
    shortName: "1 Thess",
    abbreviations: [
      "1Thess",
      "1Th",
      "1 Thessalonians",
      "1 Thess",
      "1Thessalonians",
    ],
    testament: "new",
    chapterCount: 5,
    isSingleChapter: false,
  },
  {
    id: "2TH",
    name: "2 Thessalonians",
    shortName: "2 Thess",
    abbreviations: [
      "2Thess",
      "2Th",
      "2 Thessalonians",
      "2 Thess",
      "2Thessalonians",
    ],
    testament: "new",
    chapterCount: 3,
    isSingleChapter: false,
  },
  {
    id: "1TI",
    name: "1 Timothy",
    shortName: "1 Tim",
    abbreviations: ["1Tim", "1Ti", "1 Timothy", "1 Tim", "1Timothy"],
    testament: "new",
    chapterCount: 6,
    isSingleChapter: false,
  },
  {
    id: "2TI",
    name: "2 Timothy",
    shortName: "2 Tim",
    abbreviations: ["2Tim", "2Ti", "2 Timothy", "2 Tim", "2Timothy"],
    testament: "new",
    chapterCount: 4,
    isSingleChapter: false,
  },
  {
    id: "TIT",
    name: "Titus",
    shortName: "Titus",
    abbreviations: ["Titus", "Tit"],
    testament: "new",
    chapterCount: 3,
    isSingleChapter: false,
  },
  {
    id: "PHM",
    name: "Philemon",
    shortName: "Phlm",
    abbreviations: ["Phlm", "Phm", "Philemon"],
    testament: "new",
    chapterCount: 1,
    isSingleChapter: true,
  },
  {
    id: "HEB",
    name: "Hebrews",
    shortName: "Heb",
    abbreviations: ["Heb"],
    testament: "new",
    chapterCount: 13,
    isSingleChapter: false,
  },
  {
    id: "JAS",
    name: "James",
    shortName: "Jas",
    abbreviations: ["Jas", "Jam"],
    testament: "new",
    chapterCount: 5,
    isSingleChapter: false,
  },
  {
    id: "1PE",
    name: "1 Peter",
    shortName: "1 Pet",
    abbreviations: ["1Pet", "1Pe", "1 Peter", "1 Pet", "1Peter"],
    testament: "new",
    chapterCount: 5,
    isSingleChapter: false,
  },
  {
    id: "2PE",
    name: "2 Peter",
    shortName: "2 Pet",
    abbreviations: ["2Pet", "2Pe", "2 Peter", "2 Pet", "2Peter"],
    testament: "new",
    chapterCount: 3,
    isSingleChapter: false,
  },
  {
    id: "1JN",
    name: "1 John",
    shortName: "1 John",
    abbreviations: ["1John", "1Jn", "1 John", "1Jo"],
    testament: "new",
    chapterCount: 5,
    isSingleChapter: false,
  },
  {
    id: "2JN",
    name: "2 John",
    shortName: "2 John",
    abbreviations: ["2John", "2Jn", "2 John", "2Jo"],
    testament: "new",
    chapterCount: 1,
    isSingleChapter: true,
  },
  {
    id: "3JN",
    name: "3 John",
    shortName: "3 John",
    abbreviations: ["3John", "3Jn", "3 John", "3Jo"],
    testament: "new",
    chapterCount: 1,
    isSingleChapter: true,
  },
  {
    id: "JUD",
    name: "Jude",
    shortName: "Jude",
    abbreviations: ["Jude", "Jd"],
    testament: "new",
    chapterCount: 1,
    isSingleChapter: true,
  },
  {
    id: "REV",
    name: "Revelation",
    shortName: "Rev",
    abbreviations: ["Rev", "Re"],
    testament: "new",
    chapterCount: 22,
    isSingleChapter: false,
  },
] as const;

/** Books grouped by testament for picker UI */
export const OLD_TESTAMENT_BOOKS = BIBLE_BOOKS.filter(
  (b) => b.testament === "old"
);
export const NEW_TESTAMENT_BOOKS = BIBLE_BOOKS.filter(
  (b) => b.testament === "new"
);

/** Lookup map: lowercased name/abbreviation -> BibleBook */
const bookLookupMap = new Map<string, BibleBook>();
for (const book of BIBLE_BOOKS) {
  bookLookupMap.set(book.name.toLowerCase(), book);
  bookLookupMap.set(book.shortName.toLowerCase(), book);
  bookLookupMap.set(book.id.toLowerCase(), book);
  for (const abbr of book.abbreviations) {
    bookLookupMap.set(abbr.toLowerCase(), book);
  }
}

/**
 * Find a BibleBook by name, abbreviation, or ID (case-insensitive).
 * Handles both spaced ("1 John") and concatenated ("1John") forms.
 */
export const getBookByNameOrAbbreviation = (
  input: string
): BibleBook | undefined => {
  return bookLookupMap.get(input.toLowerCase());
};

/** Find a BibleBook by its canonical ID (e.g. "GEN", "1JN") */
export const getBookById = (id: string): BibleBook | undefined => {
  return BIBLE_BOOKS.find((b) => b.id === id);
};

/** Total chapter count across all books (useful for progress calculations) */
export const TOTAL_BIBLE_CHAPTERS = BIBLE_BOOKS.reduce(
  (sum, book) => sum + book.chapterCount,
  0
);
