#!/bin/sh

hook_bootstrap="$(dirname "$0")/_/husky.sh"
if [ -f "$hook_bootstrap" ]; then
  . "$hook_bootstrap"
fi

# Typecheck
npx tsc --noEmit

# Lint
npm run lint

# Format staged files
npx lint-staged
