name: Create Development Builds
on:
  push:
    branches: develop
jobs:
  quality-check:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Packages
        run: yarn install
      - name: Typecheck
        run: npx --no-install tsc --noEmit
      - name: Lint
        run: yarn lint
  deploy_develop:
    name: Deploy To Development Release Channel
    needs: quality-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          expo-version: 4.x
          eas-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Packages
        run: yarn install
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: ${{ steps.previous-release.outputs.rev }}
      - name: Stage Expo Updates on Development
        run: npx eas-cli update --non-interactive --branch development --message "${{ steps.changelog.outputs.changelog }}"
  build_all_platforms:
    name: Build All Platforms (iOS and Android)
    needs: deploy_develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          expo-version: 4.x
          eas-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Packages
        run: yarn install --pure-lockfile
      - name: Build iOS Release
        run: |
          npx eas-cli build --platform all --profile development --non-interactive
