name: Create Production Release
on:
  push:
    branches: production
jobs:
  quality-check:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install Packages
        run: yarn install
      - name: Typecheck
        run: npx --no-install tsc --noEmit
      - name: Lint
        run: yarn lint
  deploy_prod:
    name: Stage Expo Updates
    needs: quality-check
    runs-on: ubuntu-latest
    outputs:
      latestBinaryVersion: ${{ steps.latestBinaryVersion.outputs.version }}
      isMajorRelease: ${{ steps.determineMajorRelease.outputs.isMajorRelease }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch Tags
        run: |
          git fetch --prune --unshallow --tags -f
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          expo-version: 4.x
          eas-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Packages
        run: yarn install
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}
          base-ref: ${{ steps.previous-release.outputs.rev }}
      - name: Stage Expo Updates on Production
        run: npx eas-cli update --non-interactive --branch production --message "${{ steps.changelog.outputs.changelog }}"
  build_android:
    needs: deploy_prod
    runs-on: ubuntu-latest
    outputs:
      androidBuildInfo: ${{ steps.androidInfo.outputs.buildInfo }}
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          expo-version: 4.x
          eas-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Packages
        run: yarn install --pure-lockfile
      - name: Build Android Release
        run: |
          npx eas-cli build --platform android --profile production --non-interactive > ../buildLogAndroid.txt
          cat ../buildLogAndroid.txt
      - name: Gather build info
        id: androidInfo
        run: |
          BUILD_INFO=$(cat ../buildLogAndroid.txt | tail | egrep -A1 'Android app:')
          echo $BUILD_INFO
          echo "::set-output name=buildInfo::$BUILD_INFO"
  build_ios:
    needs: deploy_prod
    runs-on: ubuntu-latest
    outputs:
      iosBuildInfo: ${{ steps.iosInfo.outputs.buildInfo }}
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          expo-version: 4.x
          eas-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install Packages
        run: yarn install --pure-lockfile
      - name: Build iOS Release
        run: |
          npx eas-cli build --platform ios --profile production --non-interactive > ../buildLogIOS.txt
          cat ../buildLogIOS.txt
      - name: Gather build info
        id: iosInfo
        run: |
          BUILD_INFO=$(cat ../buildLogIOS.txt | tail | egrep -A1 'iOS app:')
          echo $BUILD_INFO
          echo "::set-output name=buildInfo::$BUILD_INFO"
